/**
 * Email Sender Module - Config-driven branded email sender
 *
 * Features:
 * - Client-specific branding (colors, logo, footer)
 * - Outlook-safe table-based HTML layout
 * - Inline logo embedding via Microsoft Graph
 * - Markdown-to-HTML conversion with inline styles
 *
 * Usage:
 *   const { sendReport, sendTestEmail } = require('../core/lib/email-sender');
 *   await sendReport(config, 'dod', reportContent, reportPath, meta);
 */

const { marked } = require('marked');
const fs = require('fs');
const path = require('path');

/**
 * Default color palette (can be overridden per client via config.client.branding.colors)
 */
const DEFAULT_COLORS = {
    outerBg: '#f5f5f5',
    containerBg: '#ffffff',
    headerBar: '#1a365d',
    headerText: '#ffffff',
    headerSubtext: '#e2e8f0',
    border: '#e2e8f0',
    primaryText: '#333333',
    headingH1: '#1a365d',
    headingH2: '#2d3748',
    headingH3: '#4a5568',
    mutedText: '#718096',
    tableHeaderBg: '#1a365d',
    tableHeaderText: '#ffffff',
    tableRowAlt: '#f7fafc',
    accent: '#3182ce'
};

/**
 * Category-based row colors for call grid (Appendix A)
 */
const CATEGORY_COLORS = {
    'booked': '#d4edda',
    'abandoned': '#fff3cd',
    'frustrated': '#fff3cd',
    'book-xfer': '#ffeeba',
    'transfer': '#e2e3e5',
    'spam': '#f5f5f5',
    'hangup': '#f8d7da'
};

/**
 * Resolve the color palette for a client config
 */
function resolveColors(config) {
    const brandingColors = config.client.branding?.colors || {};
    return { ...DEFAULT_COLORS, ...brandingColors };
}

/**
 * Wrap HTML content with branded email chrome
 * @param {string} innerHtml - The converted markdown HTML
 * @param {Object} meta - Metadata (titleLine, generatedTs, dateRange, etc.)
 * @param {Object} config - Client configuration
 * @returns {string} - Complete HTML email document
 */
function wrapWithEmailChrome(innerHtml, meta = {}, config = {}) {
    const COLORS = resolveColors(config);
    const clientName = config.client.name || 'Report';
    const aiName = config.client.aiAssistantName || 'AI Assistant';
    const titleLine = meta.titleLine || 'Day-Over-Day Call Summary';
    const timezone = config.client.timezone || 'America/New_York';
    const generatedTs = meta.generatedTs || new Date().toLocaleString('en-US', { timeZone: timezone });

    const branding = config.client.branding || {};
    const emailFooter = branding.emailFooter || 'Generated by SupervizeAI, LLC | Performance Intelligence';
    const footerLink = branding.footerLink || '';
    const footerLinkText = branding.footerLinkText || `Review ${aiName}'s calls and audio`;
    const headerSubtitle = branding.headerSubtitle || `${clientName} | Daily Performance Report`;

    return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${clientName} - Performance Report</title>
</head>
<body style="margin:0;padding:0;background:${COLORS.outerBg};font-family:Arial,Helvetica,sans-serif;">
  <table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="background:${COLORS.outerBg};">
    <tr>
      <td align="center" style="padding:20px 10px;">
        <table role="presentation" width="680" cellspacing="0" cellpadding="0" border="0" style="background:${COLORS.containerBg};border:1px solid ${COLORS.border};max-width:680px;width:100%;">
          <!-- HEADER -->
          <tr>
            <td style="padding:20px 24px;background:${COLORS.headerBar};">
              <table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0">
                <tr>
                  <td width="108" valign="middle" style="width:108px;">
                    <img src="cid:client_logo" width="100" height="100" alt="${aiName}" style="display:block;width:100px;height:100px;">
                  </td>
                  <td style="padding-left:16px;" valign="middle">
                    <div style="font-size:20px;font-weight:bold;color:${COLORS.headerText};line-height:1.3;">
                      ${titleLine}
                    </div>
                    <div style="font-size:13px;color:${COLORS.headerSubtext};margin-top:4px;line-height:1.3;">
                      ${headerSubtitle}
                    </div>
                  </td>
                </tr>
              </table>
            </td>
          </tr>
          <!-- METADATA CHIPS ROW 1 -->
          <tr>
            <td style="padding:12px 24px 6px 24px;background:${COLORS.tableRowAlt};">
              <table role="presentation" cellspacing="0" cellpadding="0" border="0" style="width:100%;">
                <tr>
                  <td style="padding-right:8px;vertical-align:top;width:33%;">
                    <div style="background:#ffffff;border:1px solid ${COLORS.border};border-radius:4px;padding:6px 10px;">
                      <div style="font-size:10px;color:${COLORS.mutedText};text-transform:uppercase;letter-spacing:0.5px;margin-bottom:2px;">Generated</div>
                      <div style="font-size:12px;color:${COLORS.primaryText};font-weight:600;">${generatedTs}</div>
                    </div>
                  </td>
                  <td style="padding-right:8px;vertical-align:top;width:33%;">
                    <div style="background:#ffffff;border:1px solid ${COLORS.border};border-radius:4px;padding:6px 10px;">
                      <div style="font-size:10px;color:${COLORS.mutedText};text-transform:uppercase;letter-spacing:0.5px;margin-bottom:2px;">Calls Today</div>
                      <div style="font-size:12px;color:${COLORS.primaryText};font-weight:600;">${meta.callsToday || '-'}</div>
                    </div>
                  </td>
                  <td style="vertical-align:top;width:33%;">
                    <div style="background:#ffffff;border:1px solid ${COLORS.border};border-radius:4px;padding:6px 10px;">
                      <div style="font-size:10px;color:${COLORS.mutedText};text-transform:uppercase;letter-spacing:0.5px;margin-bottom:2px;">Today Success</div>
                      <div style="font-size:12px;color:${COLORS.primaryText};font-weight:600;">${meta.todaySuccessRate || '-'}</div>
                    </div>
                  </td>
                </tr>
              </table>
            </td>
          </tr>
          <!-- METADATA CHIPS ROW 2 -->
          <tr>
            <td style="padding:6px 24px 12px 24px;background:${COLORS.tableRowAlt};border-bottom:1px solid ${COLORS.border};">
              <table role="presentation" cellspacing="0" cellpadding="0" border="0" style="width:100%;">
                <tr>
                  <td style="padding-right:8px;vertical-align:top;width:33%;">
                    <div style="background:#ffffff;border:1px solid ${COLORS.border};border-radius:4px;padding:6px 10px;">
                      <div style="font-size:10px;color:${COLORS.mutedText};text-transform:uppercase;letter-spacing:0.5px;margin-bottom:2px;">Date Range</div>
                      <div style="font-size:12px;color:${COLORS.primaryText};font-weight:600;">${meta.dateRange || '-'}</div>
                    </div>
                  </td>
                  <td style="padding-right:8px;vertical-align:top;width:33%;">
                    <div style="background:#ffffff;border:1px solid ${COLORS.border};border-radius:4px;padding:6px 10px;">
                      <div style="font-size:10px;color:${COLORS.mutedText};text-transform:uppercase;letter-spacing:0.5px;margin-bottom:2px;">Calls in Period</div>
                      <div style="font-size:12px;color:${COLORS.primaryText};font-weight:600;">${meta.callsInPeriod || '-'}</div>
                    </div>
                  </td>
                  <td style="vertical-align:top;width:33%;">
                    <div style="background:#ffffff;border:1px solid ${COLORS.border};border-radius:4px;padding:6px 10px;">
                      <div style="font-size:10px;color:${COLORS.mutedText};text-transform:uppercase;letter-spacing:0.5px;margin-bottom:2px;">Period Success</div>
                      <div style="font-size:12px;color:${COLORS.primaryText};font-weight:600;">${meta.periodSuccessRate || '-'}</div>
                    </div>
                  </td>
                </tr>
              </table>
            </td>
          </tr>
          <!-- BODY -->
          <tr>
            <td style="padding:24px;color:${COLORS.primaryText};font-size:14px;line-height:1.6;">
              ${innerHtml}
            </td>
          </tr>
          <!-- FOOTER -->
          <tr>
            <td style="padding:16px 24px;background:${COLORS.tableRowAlt};border-top:1px solid ${COLORS.border};">
              <div style="font-size:12px;color:${COLORS.mutedText};text-align:center;line-height:1.6;">
                ${emailFooter}<br>
                ${footerLink ? `<a href="${footerLink}" style="color:${COLORS.accent};text-decoration:underline;">${footerLinkText}</a>` : ''}
              </div>
            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
</body>
</html>`;
}

/**
 * Convert markdown to styled HTML with inline styles for email compatibility
 * @param {string} markdown - Markdown content
 * @param {Object} config - Client configuration (for colors)
 * @returns {string} - Styled HTML
 */
function markdownToHtml(markdown, config = {}) {
    const COLORS = resolveColors(config);

    marked.setOptions({ gfm: true, breaks: false, tables: true });

    let html = marked(markdown);

    // Headings
    html = html.replace(/<h1>/g, `<h1 style="font-size:20px;font-weight:bold;color:${COLORS.headingH1};margin:20px 0 12px 0;padding-bottom:6px;border-bottom:2px solid ${COLORS.headingH1};">`);
    html = html.replace(/<h2>/g, `<h2 style="font-size:17px;font-weight:bold;color:${COLORS.headingH2};margin:16px 0 8px 0;padding-bottom:4px;border-bottom:1px solid ${COLORS.border};">`);
    html = html.replace(/<h3>/g, `<h3 style="font-size:15px;font-weight:bold;color:${COLORS.headingH3};margin:12px 0 6px 0;">`);
    html = html.replace(/<h4>/g, `<h4 style="font-size:14px;font-weight:bold;color:${COLORS.headingH3};margin:10px 0 4px 0;">`);

    // Paragraphs
    html = html.replace(/<p>/g, `<p style="margin:0 0 10px 0;line-height:1.5;color:${COLORS.primaryText};">`);

    // Lists
    html = html.replace(/<ul>/g, `<ul style="margin:0 0 12px 0;padding-left:20px;color:${COLORS.primaryText};">`);
    html = html.replace(/<ol>/g, `<ol style="margin:0 0 12px 0;padding-left:20px;color:${COLORS.primaryText};">`);
    html = html.replace(/<li>/g, `<li style="margin:3px 0;line-height:1.4;">`);

    // Tables
    html = html.replace(/<table>/g, `<table role="presentation" cellspacing="0" cellpadding="0" border="0" style="width:100%;border-collapse:collapse;margin:12px 0;font-size:13px;">`);
    html = html.replace(/<th>/g, `<th style="background:${COLORS.tableHeaderBg};color:${COLORS.tableHeaderText};padding:10px 12px;text-align:left;font-weight:700;font-size:14px;border:1px solid ${COLORS.border};">`);
    html = html.replace(/<th align="right">/g, `<th style="background:${COLORS.tableHeaderBg};color:${COLORS.tableHeaderText};padding:10px 12px;text-align:right;font-weight:700;font-size:14px;border:1px solid ${COLORS.border};">`);
    html = html.replace(/<th align="center">/g, `<th style="background:${COLORS.tableHeaderBg};color:${COLORS.tableHeaderText};padding:10px 12px;text-align:center;font-weight:700;font-size:14px;border:1px solid ${COLORS.border};">`);
    html = html.replace(/<td>/g, `<td style="padding:8px 12px;border:1px solid ${COLORS.border};color:${COLORS.primaryText};">`);
    html = html.replace(/<td align="right">/g, `<td style="padding:8px 12px;border:1px solid ${COLORS.border};color:${COLORS.primaryText};text-align:right;">`);
    html = html.replace(/<td align="center">/g, `<td style="padding:8px 12px;border:1px solid ${COLORS.border};color:${COLORS.primaryText};text-align:center;">`);

    // Bold
    html = html.replace(/<strong>/g, `<strong style="font-weight:600;color:${COLORS.headingH2};">`);

    // Code
    html = html.replace(/<code>/g, `<code style="background:#f4f4f4;padding:2px 6px;border-radius:3px;font-family:Consolas,Monaco,monospace;font-size:13px;">`);

    // Blockquotes
    html = html.replace(/<blockquote>/g, `<blockquote style="margin:8px 0;padding:8px 16px;border-left:3px solid ${COLORS.accent};background:${COLORS.tableRowAlt};color:${COLORS.mutedText};font-style:italic;">`);

    // Horizontal rules - Outlook-safe spacer rows
    const spacerRow = `<table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0"><tr><td height="16" style="line-height:16px;font-size:1px;">&nbsp;</td></tr></table>`;
    html = html.replace(/<hr>/g, spacerRow);
    html = html.replace(/<hr \/>/g, spacerRow);

    // Spacer rows before h2 sections
    const h2Spacer = `<table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0"><tr><td height="20" style="line-height:20px;font-size:1px;">&nbsp;</td></tr></table>`;
    html = html.replace(/<h2 style=/g, `${h2Spacer}<h2 style=`);

    // Category-based row coloring in tbody
    html = html.replace(/<tbody>([\s\S]*?)<\/tbody>/g, (tbodyMatch, tbodyContent) => {
        let rowIndex = 0;
        const styledRows = tbodyContent.replace(/<tr>([\s\S]*?)<\/tr>/g, (rowMatch, rowContent) => {
            rowIndex++;
            let bgColor = rowIndex % 2 === 0 ? COLORS.tableRowAlt : COLORS.containerBg;

            if (rowContent.includes('\u2713 booked')) {
                bgColor = CATEGORY_COLORS.booked;
            } else if (rowContent.includes('\u26a0 abandoned') || rowContent.includes('\u26a0 frustrated')) {
                bgColor = CATEGORY_COLORS.abandoned;
            } else if (rowContent.includes('\u2192 book-xfer')) {
                bgColor = CATEGORY_COLORS['book-xfer'];
            } else if (rowContent.includes('\u2192 transfer')) {
                bgColor = CATEGORY_COLORS.transfer;
            } else if (rowContent.includes('\u2717 spam')) {
                bgColor = CATEGORY_COLORS.spam;
            } else if (rowContent.includes('\u21a9 hangup')) {
                bgColor = CATEGORY_COLORS.hangup;
            }

            return `<tr style="background:${bgColor};">${rowContent}</tr>`;
        });
        return `<tbody>${styledRows}</tbody>`;
    });

    return html;
}

/**
 * Format subject line with date/time placeholders
 */
function formatSubject(template, config) {
    const timezone = config.client.timezone || 'America/New_York';
    const now = new Date();
    const dateStr = now.toLocaleDateString('en-US', {
        month: 'short', day: 'numeric', year: 'numeric', timeZone: timezone
    });
    const timeStr = now.toLocaleTimeString('en-US', {
        hour: 'numeric', minute: '2-digit', timeZone: timezone
    });

    return template
        .replace('{date}', dateStr)
        .replace('{time}', timeStr)
        .replace('{clientName}', config.client.name || '')
        .replace('{aiName}', config.client.aiAssistantName || '');
}

/**
 * Load and encode the client logo as base64
 * @param {Object} config - Client configuration
 * @returns {string|null} - Base64 encoded image or null if not found
 */
function loadLogoBase64(config) {
    const branding = config.client.branding || {};
    const clientDir = config.paths.clientDir;

    // Build search paths from config or defaults
    const searchPaths = [];

    if (branding.logoPath) {
        // Resolve relative to client directory
        searchPaths.push(path.resolve(clientDir, branding.logoPath));
    }

    // Default search paths
    const aiName = (config.client.aiAssistantName || 'logo').toLowerCase();
    searchPaths.push(
        path.join(clientDir, 'assets', `${aiName}_logo.png`),
        path.join(clientDir, 'assets', `${aiName}.png`),
        path.join(clientDir, 'assets', 'logo.png'),
        path.join(clientDir, `${aiName}_logo.png`)
    );

    for (const logoPath of searchPaths) {
        if (fs.existsSync(logoPath)) {
            try {
                const logoBuffer = fs.readFileSync(logoPath);
                return logoBuffer.toString('base64');
            } catch (err) {
                console.warn(`[Email] Could not read logo from ${logoPath}: ${err.message}`);
            }
        }
    }

    console.warn('[Email] Client logo not found, email will use alt text');
    return null;
}

/**
 * Send email via Microsoft Graph with inline logo attachment
 */
async function sendViaMSGraph(to, cc, subject, htmlBody, from, logoBase64, config) {
    const { ClientSecretCredential } = require('@azure/identity');
    const { Client } = require('@microsoft/microsoft-graph-client');
    const { TokenCredentialAuthenticationProvider } = require('@microsoft/microsoft-graph-client/authProviders/azureTokenCredentials');

    const credential = new ClientSecretCredential(
        process.env.AZURE_TENANT_ID,
        process.env.AZURE_CLIENT_ID,
        process.env.AZURE_CLIENT_SECRET
    );

    const authProvider = new TokenCredentialAuthenticationProvider(credential, {
        scopes: ['https://graph.microsoft.com/.default']
    });

    const graphClient = Client.initWithMiddleware({ authProvider });

    const message = {
        subject: subject,
        body: { contentType: 'HTML', content: htmlBody },
        toRecipients: (Array.isArray(to) ? to : [to]).map(email => ({
            emailAddress: { address: email }
        })),
        ccRecipients: (cc && cc.length > 0)
            ? (Array.isArray(cc) ? cc : [cc]).map(email => ({ emailAddress: { address: email } }))
            : []
    };

    if (logoBase64) {
        const logoName = `${(config.client.aiAssistantName || 'logo').toLowerCase()}_logo.png`;
        message.attachments = [{
            '@odata.type': '#microsoft.graph.fileAttachment',
            name: logoName,
            contentType: 'image/png',
            isInline: true,
            contentId: 'client_logo',
            contentBytes: logoBase64
        }];
    }

    await graphClient
        .api(`/users/${from}/sendMail`)
        .post({ message: message, saveToSentItems: true });

    return { success: true };
}

/**
 * Send a report with client branding
 * @param {Object} config - Full client configuration (from loadClientConfig)
 * @param {string} reportType - 'dod', 'intraday', etc.
 * @param {string} reportContent - Markdown content of the report
 * @param {string} reportPath - Path to the report file (for reference)
 * @param {Object} meta - Metadata (titleLine, generatedTs, dateRange, etc.)
 * @returns {Promise<object>} - Send result
 */
async function sendReport(config, reportType, reportContent, reportPath = null, meta = {}) {
    const emailConfig = config.client.email;
    if (!emailConfig) {
        throw new Error('No email configuration found in client config. Add an "email" section to client.json.');
    }

    // Get subject template
    const subjectTemplate = emailConfig.subjects?.[reportType]
        || emailConfig.subjects?.dod
        || `${config.client.name} - ${reportType.toUpperCase()} Report ({date})`;
    const subject = formatSubject(subjectTemplate, config);

    // Convert markdown to styled HTML
    const innerHtml = markdownToHtml(reportContent, config);

    // Wrap with branded email chrome
    const fullHtml = wrapWithEmailChrome(innerHtml, meta, config);

    // Load logo
    const logoBase64 = loadLogoBase64(config);

    // Resolve recipients
    const recipients = emailConfig.toProduction || emailConfig.to;
    const ccRecipients = emailConfig.ccProduction || emailConfig.cc;

    if (!recipients || recipients.length === 0) {
        throw new Error('No email recipients configured. Set "email.toProduction" or "email.to" in client.json.');
    }

    console.log(`[Email] Sending ${reportType} report to: ${recipients.join(', ')}`);
    if (ccRecipients && ccRecipients.length > 0) {
        console.log(`[Email] CC: ${ccRecipients.join(', ')}`);
    }
    console.log(`[Email] Logo: ${logoBase64 ? 'Embedded inline' : 'Not found (using alt text)'}`);

    // Check for required Azure credentials
    if (!process.env.AZURE_CLIENT_ID || !process.env.AZURE_CLIENT_SECRET || !process.env.AZURE_TENANT_ID) {
        throw new Error('Azure credentials not configured. Email requires AZURE_CLIENT_ID, AZURE_CLIENT_SECRET, and AZURE_TENANT_ID.');
    }

    try {
        const result = await sendViaMSGraph(
            recipients,
            ccRecipients,
            subject,
            fullHtml,
            emailConfig.from,
            logoBase64,
            config
        );

        console.log('[Email] Sent successfully via Microsoft Graph!');
        return result;
    } catch (error) {
        console.error(`[Email] Failed to send: ${error.message}`);
        throw error;
    }
}

/**
 * Send a test email to verify branding and delivery
 * @param {Object} config - Full client configuration
 */
async function sendTestEmail(config) {
    const aiName = config.client.aiAssistantName || 'AI Assistant';

    const testMarkdown = `# Test Report

## Executive Overview

### Today
- This is a **test email** to verify email formatting.
- Processed **0** calls (this is a test).
- All systems operational.

### What changed
- Nothing changed - this is a test.

### Why it matters
- Verifying email rendering in Outlook.
- Checking inline logo display.

### Recommended actions
- Review this email in Outlook Desktop.
- Review this email in Outlook Web.
- Confirm logo appears inline.

## Sample Table

| Metric | Value | Status |
|--------|-------|--------|
| Test 1 | 100 | Pass |
| Test 2 | 200 | Pass |
| Test 3 | 300 | Pass |

## Notes

This email was generated by the generic email sender module for **${config.client.name}**.
`;

    const meta = {
        titleLine: `Test Email - ${aiName} Format Verification`,
        generatedTs: new Date().toLocaleString('en-US', { timeZone: config.client.timezone || 'America/New_York' }),
        dateRange: 'N/A (Test)'
    };

    return sendReport(config, 'dod', testMarkdown, null, meta);
}

module.exports = {
    sendReport,
    sendTestEmail,
    markdownToHtml,
    wrapWithEmailChrome,
    loadLogoBase64,
    DEFAULT_COLORS,
    CATEGORY_COLORS
};
